apiVersion: v1
kind: Service

metadata:
  name: config-server

spec:

  selector:
    app: config-server

  ports:

  - port: {{ .Values.services.config.port }}

    targetPort: {{ .Values.services.config.port }}

  type: ClusterIP
