apiVersion: v1
kind: Service

metadata:
  name: discovery-server
  labels:
    monitoring: enabled

spec:

  selector:
    app: discovery-server

  ports:

  - port: {{ .Values.services.discovery.port }}
    name: http

    targetPort: {{ .Values.services.discovery.port }}

  type: ClusterIP
