apiVersion: v1
kind: Service

metadata:
  name: discovery-server

spec:

  selector:
    app: discovery-server

  ports:

  - port: {{ .Values.services.discovery.port }}

    targetPort: {{ .Values.services.discovery.port }}

  type: ClusterIP
