apiVersion: v1
kind: Service

metadata:
  name: notification-service
  labels:
    monitoring: enabled

spec:

  selector:
    app: notification-service

  ports:

  - port: {{ .Values.services.notification.port }}
    name: http

    targetPort: {{ .Values.services.notification.port }}

  type: ClusterIP
