apiVersion: v1
kind: Service

metadata:
  name: order-service
  labels:
    monitoring: enabled

spec:

  selector:
    app: order-service

  ports:

  - port: {{ .Values.services.order.port }}
    name: http

    targetPort: {{ .Values.services.order.port }}

  type: ClusterIP
