apiVersion: v1
kind: Service

metadata:
  name: payment-service
  labels:
    monitoring: enabled

spec:

  selector:
    app: payment-service

  ports:

  - port: {{ .Values.services.payment.port }}
    name: http

    targetPort: {{ .Values.services.payment.port }}

  type: ClusterIP
