apiVersion: v1
kind: Service

metadata:
  name: product-service
  labels:
    monitoring: enabled

spec:

  selector:
    app: product-service

  ports:

  - port: {{ .Values.services.product.port }}
    name: http

    targetPort: {{ .Values.services.product.port }}

  type: ClusterIP
