apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service

          image: "user-service:1.1"
          imagePullPolicy: Never

          ports:
            - containerPort: {{ .Values.services.user.port }}

          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888

            - name: EUREKA_URL
              value: http://discovery-server:8761/eureka
