server:
  port: 8083

spring:
  application:
    name: user-service

  config:
    import: "configserver:http://config-server:8888"

  cloud:
    config:
      uri: http://config-server:8888
      name: user-service
      profile: default
      label: main
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
