apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: enterprise-ecommerce
  labels:
    app: discovery-server

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discovery-server

  template:
    metadata:
      labels:
        app: discovery-server

    spec:
      containers:
      - name: discovery-server
        image: discovery-server:1.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8761

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
