apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: enterprise-ecommerce
  labels:
    app: config-server

spec:
  replicas: 1

  selector:
    matchLabels:
      app: config-server

  template:
    metadata:
      labels:
        app: config-server

    spec:
      containers:
      - name: config-server
        image: config-server:1.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8888

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
